### ISSUE TITLE
this.jPushPlugin.reSetBadge() 调用失败

### ISSUE THREAD

**Issue by shenopkss** [HsuanXyz/ionic2-jpush#3]
Hi HsuanXyz，非常感谢您的分享，我使用中遇到如下错误，希望您的帮助：
```
this.jPushPlugin.init()
    .then(res => {
        //移除badge 仅 ios
        this.jPushPlugin.reSetBadge().then(res => {
          console.log('jPushPlugin reSetBadge success');
          console.log(res)
        }).catch(err => {
          console.log('jPushPlugin reSetBadge error');
          console.log(err)
        });
})
```

调用失败，打印catch err 无任何显示

**Comment by hsuanxyz** [comment]
嗨，晚上好。调用init之后能获取到极光注册ID吗

2017年6月9日 上午12:58，"shenopkss" <notifications@github.com>写道：

Hi HsuanXyz，非常感谢您的分享，我使用中遇到如下错误，希望您的帮助：

this.jPushPlugin.init()
    .then(res => {
        //移除badge 仅 ios
        this.jPushPlugin.reSetBadge().then(res => {
          console.log('jPushPlugin reSetBadge success');
          console.log(res)
        }).catch(err => {
          console.log('jPushPlugin reSetBadge error');
          console.log(err)
        });
})

调用失败，打印catch err 无任何显示

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HsuanXyz/ionic2-jpush/issues/3>, or mute the thread

**Comment by shenopkss** [comment]
@HsuanXyz init之后能获取极光ID。
我可能搞错了，我尝试修改调用setApplicationIconBadgeNumber方法，解决了我的问题，非常感谢您的回复！

**Comment by hsuanxyz** [comment]
请更新到新版本，并查看最新文档。
